### PR TITLE
Relax dependency constraints

### LINKED ISSUE #12: Make the dependencies looser
It would be very cool if you could make the dependencies of this project (such as requests and docutils) more looser, so I could the snooty-lexstudio to my dev-dependencies with less hassle.

For example, you currently accept: requests >=2.24.0,<2.25.0. I believe you could safely accept >=2.24.0,<3.0.0 for example.

```sh-session
$ poetry add --dev snooty-lextudio
Using version ^1.8.6-alpha.0 for snooty-lextudio

Updating dependencies
Resolving dependencies... (0.2s)

  SolverProblemError

  Because no versions of snooty-lextudio match >1.8.6-alpha.0,<2.0.0
   and snooty-lextudio (1.8.6.dev0) depends on requests (>=2.24.0,<2.25.0), snooty-lextudio (>=1.8.6-alpha.0,<2.0.0) requires requests (>=2.24.0,<2.25.0).
  So, because river-cicd depends on both requests (^2.25.1) and snooty-lextudio (^1.8.6-alpha.0), version solving failed.
```

### PR DESCRIPTION
**Pull request by ofek**
Resolves #12 

@lextm Can you please take a look? We want to use this but cannot until a version is released with looser dependency constraints.

### CODE REVIEW

**Comment by alexchandel** [comment]
@lextm  Please merge.  The overly strict `pyyaml`, `requests`, and `watchdog` dependencies are blocking me.

**Comment by staticdev** [comment]
@lextm LGTM please. I need that to upgrade my requests file.

**Comment by lextm** [comment]
Will not take this pull request, but merge the changes from upstream in the coming days.

**Comment by felipecrs** [comment]
>Thanks, but will not take this pull request. Plan to merge the changes from upstream in the coming days.

@lextm is it still in the plans?

**Comment by lextm** [comment]
The upstream changes have been merged earlier this year, https://github.com/vscode-restructuredtext/snooty-parser/blob/release/pyproject.toml

The only missing piece is `"docutils ~= 0.16"` but as long as the upstream implements that change, this fork will follow.

**Comment by felipecrs** [comment]
@lextm it's done now :-)

https://github.com/mongodb/snooty-parser/pull/302

**Pull request closed without merging**
